### ISSUE TITLE
Merge image sizes, custom templates, description field from our fork

### ISSUE THREAD

**Issue by bezin** [mindbird/contao-person#6]
Hi @Wusch 

as you know we maintain a fork of your extension. Over time we added some features we need in every project. We would like to merge them into your extension to only have on repository to work with. 

We would propose the following features:
* **Image sizes** Let editors decide which image size to use in person elements and modules and use this image size in the default templates
* **Templates** Add a dropown for a custom element or module template, like it is the default for core elements and modules since 3.3. There actually is PR #2 for that since 2016, which is now outdated obviously ;-) We would rebase our changes onto the new code structure and would resend a PR.
* **Add a description field** In every project we use this extension, we need a textarea for additional information, e.g. a short CV, personal statement. Adding this field to the core version, would help us enormously.

We think, these features come with no downside, because the default behaviour stays like it is atm. 

Love to hear what you think :-)

Best
Benedict

**Comment by Wusch** [comment]
Do it :)

**Comment by bezin** [comment]
See #8 for commits :-)

Image sizes as we proposed were actually already implemented 😎

**Comment by bezin** [comment]
This is all merged with #8 Thanks for merging 👍
